export const courses = [
  {
    title: "Coding Workshop",
    category: "Coding",
    image: "https://placehold.co/600x400@2x.png",
    lecturers: [
      {
        name: "Lynn Thit",
        title: "Assistant Professor",
        institution: "School of Information Assumption University",
      },
      {
        name: "Nyi Nyi",
        title: "Assistant Professor",
        institution: "School of Information Assumption University",
      },
    ],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget sapien egestas tincidunt.",
    topics: [
      "Introduction to Coding",
      "Basic Python",
      "Advanced Python",
      "Data Structures",
      "Algorithms",
      "Project",
    ],
    certification: true,
    rating: 4,
    reviews: 215,
    lessons: 24,
    duration: 18,
    students: 60,
  },
  {
    title: "Web Development Bootcamp",
    category: "Coding",
    image: "https://placehold.co/600x400@2x.png",
    lecturers: [
      {
        name: "John Smith",
        title: "Senior Developer",
        institution: "Tech Academy",
      },
      {
        name: "John Smith",
        title: "Senior Developer",
        institution: "Tech Academy",
      },
    ],
    description:
      "Learn how to build modern websites using HTML, CSS, and JavaScript. Includes a project-based approach.",
    topics: [
      "HTML Basics",
      "CSS Essentials",
      "Responsive Design",
      "JavaScript for the Web",
      "Building a Portfolio Website",
    ],
    certification: true,
    rating: 4.5,
    reviews: 320,
    lessons: 30,
    duration: 20,
    students: 100,
  },
  {
    title: "Data Science Essentials",
    category: "Coding",
    image: "https://placehold.co/600x400@2x.png",
    lecturers: [
      {
        name: "John Smith",
        title: "Senior Developer",
        institution: "Tech Academy",
      },
      {
        name: "Jane Doe",
        title: "Data Scientist",
        institution: "Global Analytics Institute",
      },
    ],
    description:
      "Discover the fundamentals of data science, from data wrangling to machine learning basics.",
    topics: [
      "Introduction to Data Science",
      "Data Wrangling",
      "Exploratory Data Analysis",
      "Statistical Methods",
      "Introduction to Machine Learning",
    ],
    certification: true,
    rating: 4.7,
    reviews: 150,
    lessons: 28,
    duration: 24,
    students: 80,
  },
  {
    title: "Graphic Design Fundamentals",
    category: "Coding",
    image: "https://placehold.co/600x400@2x.png",
    lecturers: [
      {
        name: "John Smith",
        title: "Senior Developer",
        institution: "Tech Academy",
      },
      {
        name: "Emily Lee",
        title: "Graphic Designer",
        institution: "Creative Design Academy",
      },
    ],
    description:
      "Learn the basics of graphic design and how to create stunning visuals using popular design tools.",
    topics: [
      "Principles of Design",
      "Color Theory",
      "Typography Basics",
      "Introduction to Adobe Photoshop",
      "Creating Digital Art",
    ],
    certification: false,
    rating: 4.3,
    reviews: 200,
    lessons: 22,
    duration: 16,
    students: 120,
  },
  {
    title: "Cloud Computing Mastery",
    category: "Coding",
    image: "https://placehold.co/600x400@2x.png",
    lecturers: [
      {
        name: "John Smith",
        title: "Senior Developer",
        institution: "Tech Academy",
      },
      {
        name: "Michael Brown",
        title: "Cloud Architect",
        institution: "Cloud Solutions Inc.",
      },
    ],
    description:
      "Gain in-depth knowledge of cloud computing, including AWS, Azure, and Google Cloud.",
    topics: [
      "Introduction to Cloud Computing",
      "AWS Basics",
      "Azure Overview",
      "Google Cloud Essentials",
      "Deploying Scalable Applications",
    ],
    certification: true,
    rating: 4.8,
    reviews: 180,
    lessons: 35,
    duration: 30,
    students: 75,
  },
  {
    title: "Digital Marketing Strategies",
    category: "Coding",
    image: "https://placehold.co/600x400@2x.png",
    lecturers: [
      {
        name: "John Smith",
        title: "Senior Developer",
        institution: "Tech Academy",
      },
      {
        name: "Sarah Green",
        title: "Marketing Strategist",
        institution: "Digital Marketing Pro",
      },
    ],
    description:
      "Master the art of digital marketing with real-world strategies for social media, SEO, and more.",
    topics: [
      "SEO Fundamentals",
      "Content Marketing",
      "Social Media Marketing",
      "Email Campaigns",
      "Analyzing Marketing Data",
    ],
    certification: false,
    rating: 4.6,
    reviews: 250,
    lessons: 20,
    duration: 15,
    students: 90,
  },
  {
    title: "Cybersecurity Basics",
    category: "Coding",
    image: "https://placehold.co/600x400@2x.png",
    lecturers: [
      {
        name: "John Smith",
        title: "Senior Developer",
        institution: "Tech Academy",
      },
      {
        name: "David Johnson",
        title: "Cybersecurity Expert",
        institution: "SecureTech Academy",
      },
    ],
    description:
      "Learn the essentials of cybersecurity, including threat detection and prevention techniques.",
    topics: [
      "Understanding Cyber Threats",
      "Network Security Basics",
      "Introduction to Ethical Hacking",
      "Securing Personal Devices",
      "Incident Response",
    ],
    certification: true,
    rating: 4.4,
    reviews: 130,
    lessons: 25,
    duration: 20,
    students: 50,
  },
  {
    title: "Artificial Intelligence for Beginners",
    category: "Coding",
    image: "https://placehold.co/600x400@2x.png",
    lecturers: [
      {
        name: "Sophia Martinez",
        title: "AI Researcher",
        institution: "NextGen AI Lab",
      },
    ],
    description:
      "An introductory course to artificial intelligence, covering basic concepts, tools, and real-world applications.",
    topics: [
      "History of AI",
      "Machine Learning Basics",
      "Neural Networks Overview",
      "AI Tools and Frameworks",
      "Ethics in AI",
    ],
    certification: true,
    rating: 4.9,
    reviews: 170,
    lessons: 26,
    duration: 22,
    students: 85,
  },
];

export const popularCurses = [
  {
    title: "Coding Workshop",
    category: "Coding",
    image: "https://placehold.co/600x400@2x.png",
    lecturers: [
      {
        name: "Lynn Thit",
        title: "Assistant Professor",
        institution: "School of Information Assumption University",
      },
      {
        name: "Nyi Nyi",
        title: "Assistant Professor",
        institution: "School of Information Assumption University",
      },
    ],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget sapien egestas tincidunt.",
    topics: [
      "Introduction to Coding",
      "Basic Python",
      "Advanced Python",
      "Data Structures",
      "Algorithms",
      "Project",
    ],
    certification: true,
    rating: 4,
    reviews: 215,
    lessons: 24,
    duration: 18,
    students: 60,
  },
  {
    title: "Web Development",
    category: "Coding",
    image: "https://placehold.co/600x400@2x.png",
    lecturers: [
      {
        name: "John Smith",
        title: "Senior Developer",
        institution: "Tech Academy",
      },
      {
        name: "John Smith",
        title: "Senior Developer",
        institution: "Tech Academy",
      },
    ],
    description:
      "Learn how to build modern websites using HTML, CSS, and JavaScript. Includes a project-based approach.",
    topics: [
      "HTML Basics",
      "CSS Essentials",
      "Responsive Design",
      "JavaScript for the Web",
      "Building a Portfolio Website",
    ],
    certification: true,
    rating: 4.5,
    reviews: 320,
    lessons: 30,
    duration: 20,
    students: 100,
  },
  {
    title: "Data Science",
    category: "Coding",
    image: "https://placehold.co/600x400@2x.png",
    lecturers: [
      {
        name: "John Smith",
        title: "Senior Developer",
        institution: "Tech Academy",
      },
      {
        name: "Jane Doe",
        title: "Data Scientist",
        institution: "Global Analytics Institute",
      },
    ],
    description:
      "Discover the fundamentals of data science, from data wrangling to machine learning basics.",
    topics: [
      "Introduction to Data Science",
      "Data Wrangling",
      "Exploratory Data Analysis",
      "Statistical Methods",
      "Introduction to Machine Learning",
    ],
    certification: true,
    rating: 4.7,
    reviews: 150,
    lessons: 28,
    duration: 24,
    students: 80,
  },
  {
    title: "Graphic Design",
    category: "Coding",
    image: "https://placehold.co/600x400@2x.png",
    lecturers: [
      {
        name: "John Smith",
        title: "Senior Developer",
        institution: "Tech Academy",
      },
      {
        name: "Emily Lee",
        title: "Graphic Designer",
        institution: "Creative Design Academy",
      },
    ],
    description:
      "Learn the basics of graphic design and how to create stunning visuals using popular design tools.",
    topics: [
      "Principles of Design",
      "Color Theory",
      "Typography Basics",
      "Introduction to Adobe Photoshop",
      "Creating Digital Art",
    ],
    certification: false,
    rating: 4.3,
    reviews: 200,
    lessons: 22,
    duration: 16,
    students: 120,
  },
  {
    title: "Cloud Computing",
    category: "Coding",
    image: "https://placehold.co/600x400@2x.png",
    lecturers: [
      {
        name: "John Smith",
        title: "Senior Developer",
        institution: "Tech Academy",
      },
      {
        name: "Michael Brown",
        title: "Cloud Architect",
        institution: "Cloud Solutions Inc.",
      },
    ],
    description:
      "Gain in-depth knowledge of cloud computing, including AWS, Azure, and Google Cloud.",
    topics: [
      "Introduction to Cloud Computing",
      "AWS Basics",
      "Azure Overview",
      "Google Cloud Essentials",
      "Deploying Scalable Applications",
    ],
    certification: true,
    rating: 4.8,
    reviews: 180,
    lessons: 35,
    duration: 30,
    students: 75,
  },
  {
    title: "Digital Marketing",
    category: "Coding",
    image: "https://placehold.co/600x400@2x.png",
    lecturers: [
      {
        name: "John Smith",
        title: "Senior Developer",
        institution: "Tech Academy",
      },
      {
        name: "Sarah Green",
        title: "Marketing Strategist",
        institution: "Digital Marketing Pro",
      },
    ],
    description:
      "Master the art of digital marketing with real-world strategies for social media, SEO, and more.",
    topics: [
      "SEO Fundamentals",
      "Content Marketing",
      "Social Media Marketing",
      "Email Campaigns",
      "Analyzing Marketing Data",
    ],
    certification: false,
    rating: 4.6,
    reviews: 250,
    lessons: 20,
    duration: 15,
    students: 90,
  },
];
